### ISSUE TITLE
help making this work please :)

### ISSUE THREAD

**Issue by skynetPhil** [zaccolley/1bitphotobooth#1]
Hello !
great work on the script it looks all pretty straightforward but I'm getting an error when running the script :
I installed all the dependencies without errors
any idea what is the problem ?
thanks for your help!
Phil

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 62, in main
    printPhoto('photo_processed.jpg')
  File "main.py", line 54, in printPhoto
    printer.printImage(Image.open(f_in))
  File "/home/pi/Downloads/1bitphotobooth-master/thermalprinter.py", line 468, in printImage
    import Image
ImportError: No module named Image

**Comment by zoetrope69** [comment]
Haven't looked at this in a while. Maybe the module is called something different now?

https://pillow.readthedocs.io/en/latest/installation.html

Have a look through here and see if you can find anything

**Comment by zoetrope69** [comment]
Just noticed:

https://github.com/zaccolley/1bitphotobooth/blob/master/thermalprinter.py#L468

The docs say:

> Pillow >= 1.0 no longer supports “import Image”. Please use “from PIL import Image” instead.

We may need to install a version of Pillow below 1
